### ISSUE TITLE
4020 resistor is missing

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Resistors_SMD.pretty#16]

**Comment by eldarkg** [comment]
@SchrodingersGat notify

**Comment by jkriege2** [comment]
draw one up and make a PR?

**Comment by jkriege2** [comment]
... or does @SchrodingersGat have a script for those?

**Comment by SchrodingersGat** [comment]
The current resistors are not scripted. Perhaps they should be, so that can be kept up-to-date more easily...

**Comment by eldarkg** [comment]
So I don't draw it. It should be scripted

**Comment by pointhi** [comment]
if you don't mind, I can do the scripting

**Comment by eldarkg** [comment]
@pointhi ok)

**Comment by SchrodingersGat** [comment]
@pointhi  that would be fantastic :)

**Comment by SchrodingersGat** [comment]
If you're re-doing all these, can I request the following:

1. Capacitors_SMD (ceramics) should be regenerated too. There is currently a disparity between Rxxxx and Cxxxx footprints.
1. Please base the footprints on `IPC_Nominal` e.g. `R0805` (these should match the naming scheme of the currently existing footprints)
1. Ensure that each footprint has a `_HandSoldering` variant e.g `R0805_HandSoldering`
1. Ensure that each footprint has a `IPC_Least` variant e.g. `R0805_IPC_Least`
1. Ensure that each footprint has an `IPC_Most` variant e.g. `R0805_IPC_Most`

**Comment by pointhi** [comment]
I created some initial version of the script:

* https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Resistors_SMD
* https://github.com/pointhi/kicad-footprint-generator/commit/170435f0218059abe8ec0a62bac45f810618d01a

I'm using the new ```ModArgparse``` module which allows us to read definition files from ```.csv``` as well as ```.yml``` files.

This has the advantages you can edit the csv files simply using LibreOffice Calc, Excel or any other software which can create comma separated csv files. Furthermore, github displays the data as nice table.

The initial data you can find in the ```smd_chip_resistors_smd.csv``` table is build up of data found in:
* https://en.wikipedia.org/wiki/Surface-mount_technology#Two-terminal_packages
* https://de.wikipedia.org/wiki/Chip-Bauform
* current kicad pad sizes and spacings

Now we are coming to my issue: I don't know where I can find the data to (correctly) fill this table. Probably some of you can help me to give me a hint where I can find a table with the official dimensions (especially of the pads). I know there is a IPC-Calculator for such things, but I cannot really use it on Linux because of graphical glitches.

**Comment by SchrodingersGat** [comment]
@pointhi I would suggest using the current values of the resistors in the standard kicad library. We don't want to change them unnecessarily. I would not worry about IPC variants for now.

If we can script based on the current footprints, then they can be easily regenerated if we want to change dimensions

For missing footprints, these might be helpful:

* http://www.tortai-tech.com/upload/download/2011102023233369053.pdf
* https://www.venkel.com/docs/default-source/technical/resistors-landing-pattern
* http://www.vishay.com/docs/60119/landpatterns.pdf
* https://industrial.panasonic.com/cdbs/www-data/pdf/RDA0000/AOA0000COL36.pdf

**Comment by evanshultz** [comment]
And MELF resistors are also missing, aren't they? If so, and they won't be scripted (which seems like the wrong way to go), I'll make the footprints and submit a PR.

**Comment by evanshultz** [comment]
@SchrodingersGat @pointhi 
I think the script is set up and running, right? I don't see a 4020 resistor in the library, nor have I heard of one, so I suspect it's a typo of 0402. Is there any more action or can this issue be closed?

**Comment by SchrodingersGat** [comment]
Apparently they [do exist](https://www.digikey.com/products/en/resistors/chip-resistor-surface-mount/52?k=&pkeyword=&pv1291=7325&FV=ffe00034&mnonly=0&ColumnSort=0&page=1&quantity=0&ptm=0&fid=0&pageSize=100).

IIRC the script for chip parts (R / C / L) has been made by @pointhi but the values have not been filled in. If any new sizes are made, I think that the entire batch should be rescripted.

**Comment by eldarkg** [comment]
@evanshultz The issue is actual yet. Please don't close it

**Comment by poeschlr** [comment]
I created a more powerful script that creates footprints of this type. It has been used to generate the new footprints that will be used in the new footprint repo: https://github.com/KiCad/kicad-footprints/pull/3

If you are interested, either send me a datasheet that defines a 4020 resistor or wait until my script has been merged and do it your self. (by adding the definition to the correct yaml file)
https://github.com/pointhi/kicad-footprint-generator/pull/75

**Comment by evanshultz** [comment]
@poeschlr 
The link above from Oliver goes to a Digi-Key search where two manufacturers make 4020-package resistors. So if you want to include it in your script you can. However, I don't see any recommended footprints from either of the datasheets...

**Comment by poeschlr** [comment]
Ok i have been blind it seems.

The 4020 resistor has been added in commit: https://github.com/KiCad/kicad-footprints/pull/3/commits/88be441850c05fabae34e3cc6925012985f161bc

Closing this here.
