### ISSUE TITLE
Metric sizes

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Resistors_SMD.pretty#17]
It will be nice to see sizes in metric too, like this:
R_1206(3216m).

This applicable to other repos:
caps, inductors, ...

**Comment by eldarkg** [comment]
@SchrodingersGat notify

**Comment by poeschlr** [comment]
Agreed. At the least it should be indicated that 1206 references the imperial unit system.

**Comment by SchrodingersGat** [comment]
I would like a suffix such as `R_1206_3216M` but otherwise I like the idea.

**Comment by SchrodingersGat** [comment]
And specific metric footprints could then be `R_xxyyM`

**Comment by pointhi** [comment]
If you do so, you can use my scripts for chip components:

https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Resistors_SMD/smd_chip_resistors_smd.csv

**Comment by KarlZeilhofer** [comment]
We at Team14 decided explicitly to prefer metric names where possible. So we have to have a solution with these libraries. 

Has anyone a problem with just duplicating the files with metric naming?
e.g. R_1206 will be coppied to R_3216m

I think using symlinks will not work for windows users, right? 

Pointhis script could be used to update all the descriptions with a remark about imperial or metric units.

**Comment by SchrodingersGat** [comment]
@KarlZeilhofer we have been discussing this naming convention for the new library update, which is a large work in progress. 

It has been decided that for chip devices such as this, naming will be of the form:

`R_1206_3216Metric`

**Comment by KarlZeilhofer** [comment]
@SchrodingersGat WHY???
This scheme keeps the legacy format names before the correct metric names? If this decision is fixed, I will make my local copies to "normal" metric names like R_3216m
I want to make the transition away from weird units as fast as possible. The imperial unit system has no right for existance, in my opinion.

**Comment by jkriege2** [comment]
because:
1. having a douplicate is not a good solution ... just makes it harder to maintain the lib
2. I believe the imperial sizes are still the most used names ... and I think this lib should have names that people expect to see ... and I think most people will look for a 1206 resitsor, not a 3216M ... 

with the proposed naming scheme of @SchrodingersGat both names are there and we only have to maintain one footprint ...

**Comment by KarlZeilhofer** [comment]
But then please prefer the metric names.
We could also use R_3216_1206Imperial, right? Why should we go with the past?

Ask someone from europe, what size a 1206 resistor has. Most probably he doesnt know. Also everywhere else in the libs the metric system is used.

**Comment by jkriege2** [comment]
The question is whether the resistor in a certain size is usually REFERED to with the imperail or metric size ... In most datasheet that I've see the imperial size is given first and the metric seond (also the imperial size is usually used for the MPN) ... so why should we prefer the naming scheme that is used less?

Also they are usually sold by imperail names (also in german shops):
- https://www.conrad.biz/de/Search.html?search=SMD%20widerstand&searchType=REGULAR&category=%1Ft13%1Fc17441%1F0241260
- https://www.reichelt.de/index.html?ACTION=446&LA=0&SID=94WfnaMqwQATMAAFjloSkf85f759bc380690b15dc08a0dfe7fa51
- https://www.buerklin.com/de/search?q=smd%20widerstand:relevance:filteredCategoryPath:Bauelemente,%20passiv_SMD-D%C3%BCnnschichtwiderst%C3%A4nde&text=smd%20widerstand&page=4

**Comment by poeschlr** [comment]
Why do we still use imperial as the first unit?

Well to be honest most electronics engineers are still more used to the imperial size codes. (We will never make everyone happy. In this case team 17 will be a bit unhappy but in reality you have no reason to complain because metric units are mentioned.) 
Just as a bit of information: I am from a country that never really used british units. But i still think of a 0603 resistor not of a 1608. (even thought as i said before i normally only think in metric.)

Just take a look at any distributor of your choice:
RS does not even list metric size codes:
![screenshot from 2017-11-01 15-29-55](https://user-images.githubusercontent.com/18327350/32279847-1feced7a-bf1a-11e7-98d0-48cb6b0f1e21.png)
Farnell lists them second. (You see what i mean)
![screenshot from 2017-11-01 15-31-09](https://user-images.githubusercontent.com/18327350/32279871-306d895c-bf1a-11e7-8cba-9b91063a37ca.png)

**Comment by KarlZeilhofer** [comment]
Thats the point. You are "thinking" in imperial names. But that name is completely useless to you, you could also call them siz 1, 2, 3, 4, ...

Thinking logical now, will help at least future generations of electronics engineers to have a better system. Those old folks, which are not willing to adopt to a better system, should stick to the old system. Thats fine for me. But please also think about our youngstars, which have the chance to get used to the metric sizes from the very beginning. 

In the electronicts there is definetly the trend to metric units, and so we should leave the old system behind us. We have not the right to stick with something which will lead to a burden in thinking for the future generations, just because "we" are used to that.

Of course that transition is a process over many years, but let KiCad be one of the leaders of that process.

**Comment by evanshultz** [comment]
@KarlZeilhofer 
It's not anyone in particular that is thinking in a certain way; @poeschlr has shown that the *world* uses Imperial units for chip parts. And there is meaning behind it, even if you have strong subjective convictions.

I believe your comments, as a representative of the KiCad community, is understood by the KiCad library team and the decision has been made to support both unit systems in a way that also considers library maintenance. Since the naming convention has been made this case is resolved so I'm closing it.

**Comment by eldarkg** [comment]
The issue dont fixed yet. I dont think that closing this issue is a right way

**Comment by KarlZeilhofer** [comment]
@evanshultz 
Of course you are right, that in many cases the imperial units are used. Doing a quick research gave me a number of about 30-50% of the chips are named (also) in metric units. 

But as I said, the trend is definitely towards the metric system. And it is a progress over years. I think, the mixed names are a drawback for both sides. Just think about the simple case, where you fill in the footprints for various resistors in your schematic. Perhaps most of them are R1608m, but some others are 3216m. Now you will copy and paste the footprint string from one component to the next and for some of them you do a manual change from R1608m to R3216m. With the mixed naming you would be forced to change 8 digits correctly and 4 of them you are not even interested in.

When thinking about this topic, I always remember the time, when the Euro was introduced. It was hard for every one, but on the price tags, the Euro was in first place, and the old currency was on second place, in smaller letters. After some years now nobody talks about the old currency any more. 

I know, there is no perfect solution now for this issue. But doing a redundant naming doesn't help anyone. It gets an obstacle for both sides. 

We have duplicate footprints in some other placed of the library too. I'm thinking of diodes for example. You have the diodes with A-K pads and the newer format with the 1-2 pads. So why not keeping duplicates here too? As @pointhi suggested, these are generated by a script anyway. 

And I also agree with @eldarkg that this issue isn't fixed, and therefore shouldn't be closed.

**Comment by poeschlr** [comment]
Do i really need to say more:
https://forum.kicad.info/t/alternate-resistor-symbol-kicad-evaluation-for-company-use/6310

**Comment by KarlZeilhofer** [comment]
Sure you don't have to force them!
But offering both variants doesn't hurt anyone. And I'm sure, we here at Team14 are not the only one, who would prefer the metric names. 

* Don't bother users with metric names, who want to stick with the imperial names
* Don't bother users with imperial names, who want to stick with the metrical names

So the suggested R1206_3216Metric is not practical for any of the both groups. Harddisk space used by duplicates doesn't matter in this case and maintainance is done by scripts. 

So where is the problem on having duplicates?

**Comment by KarlZeilhofer** [comment]
I would do all the renaming even by hand, if I know, that it will be merged then.

**Comment by poeschlr** [comment]
What is the problem with having a slightly longer name that includes both names? In my mind this has a lot of advantages.
You can search by both names depending on your personal preference. (typing in 1608 gives you the same footprint as typing in 0603)

And for that matter is it really that bad for you that we decided to list the currently accepted standard first? (You can not force the entire user base to change their way of thinking over night.)

Another good thing about including both names in one footprint is that the user might even learn what the metric equivalent for a imperial 0603 is. If you have one footprint for metric only and one for imperial only no user will ever make the connection that 0603 equals 1608Metric.
(Are you afraid your team members will learn it the other way round? And if so: Has knowledge ever been a problem?)

Having multiple footprints for the same part just because someone prefers one name over another creates a maintenance nightmare. Just think of the case that some footprint is discovered to be wrong. We need to ensure that all of them are changed. (This is already hard enough because we have these footprints duplicated for Resistors, Capacitors, Diodes, Inductors, Fuses, ... Now multiply this by two.)

And what if tomorrow someone comes along and wants all TO-xxx footprints duplicated for all used aliases. (Believe me there are a lot of them.)
Where should we draw the line in your mind? We librarians have decided to draw it here. We don't allow duplication of any footprint just because it is known under different names in different standards.

**Comment by SchrodingersGat** [comment]
Karl while it may not be immediately apparent especially to users who aren't intimately familiar with the process here, we spend a LOT of time trying to create a consistent library that suits many use cases. We have to make many decisions on convention, and we cannot accommodate changes at the preference of a single request. Believe me we get a lot of requests. 

The current state of electronics standards favours imperial chip packages. As an Australian metric user this irks me but it is what it is.

You are welcome to curate your internal libraries how you will. Our naming scheme allows simultaneous use by both imperial and metric users. 

Please do not take this as us disagreeing with you personally. We have to stick by our convention decisions. Note that our convention moving forward is a major improvement on the current imperial only naming scheme. 

Let's not waste any more time on this, we only have so much time to dedicate to library issued and this is not going anywhere. But again, don't take this personally.
